<<<<<<< HEAD
# Generated by Django 4.1.5 on 2023-03-23 01:31
=======
# Generated by Django 4.1.5 on 2023-02-28 01:45
>>>>>>> parent of 9e76723 (I have 2 working login/ register views each)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name="Profile",
=======
            name="Company",
>>>>>>> parent of 9e76723 (I have 2 working login/ register views each)
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("profile_pic", models.ImageField(blank=True, null=True, upload_to="")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
=======
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="SignUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=20)),
                ("repeated_password", models.CharField(max_length=20)),
>>>>>>> parent of 9e76723 (I have 2 working login/ register views each)
            ],
        ),
    ]
