# Generated by Django 4.1.5 on 2023-03-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="unitProject\x07pp\\static\\images\\profile_pic_green.png",
                null=True,
                upload_to="",
                verbose_name="Profile Picture",
            ),
        ),
    ]
