# Generated by Django 4.1.5 on 2023-03-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="static/images/profile_pic_green.png",
                null=True,
                upload_to="",
                verbose_name="Profile Picture",
            ),
        ),
    ]
